name: Deploy API

on:
  push:
    branches: [main, blazor]
    paths:
      - 'abp/ShowZen/ShowZen/**'
      - 'abp/ShowZen/etc/deploy/**'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore abp/ShowZen/ShowZen/ShowZen.csproj

      - name: Build
        run: dotnet build abp/ShowZen/ShowZen/ShowZen.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish abp/ShowZen/ShowZen/ShowZen.csproj --configuration Release --no-build -o ./publish

      - name: Prepare Config Files
        run: |
          cp abp/ShowZen/etc/deploy/docker-compose.prod.yml ./publish/docker-compose.yml
          cp abp/ShowZen/etc/deploy/nginx.conf ./publish/nginx.conf

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "publish/*"
          target: "/opt/showzen/deploy-temp"
          strip_components: 1

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Move config files first
            cp /opt/showzen/deploy-temp/docker-compose.yml /opt/showzen/docker-compose.yml
            cp /opt/showzen/deploy-temp/nginx.conf /opt/showzen/nginx/nginx.conf
            
            # Remove configs from temp so we don't move them to api folder
            rm /opt/showzen/deploy-temp/docker-compose.yml
            rm /opt/showzen/deploy-temp/nginx.conf
            
            # Deploy API
            rm -rf /opt/showzen/api/*
            mv /opt/showzen/deploy-temp/* /opt/showzen/api/
            rm -rf /opt/showzen/deploy-temp
            
            # Apply Database Migrations (uses appsettings.Production.json)
            cd /opt/showzen/api
            export ASPNETCORE_ENVIRONMENT=Production
            dotnet ShowZen.dll --migrate-database || echo "Migration completed or already applied"
            
            # Restart Systemd Service
            systemctl restart showzen-api
            
            # Refresh Infra
            cd /opt/showzen
            docker compose up -d --remove-orphans postgres redis nginx
            
            # Check Health
            sleep 10
            curl -f http://localhost:5000/health-status || echo "Check health failed, check logs"
